name: CD

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Run docker Container
        run: whoami && docker up -d
          