# Goal: To deploy the built and tested image to an EC2 instance

name: CD

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted
        steps:
           - name: Code Checkout
             uses: actions/checkout@v4
            
           - name: Docker setup
             uses: docker/setup-docker-action@v5

           - name: Docker Login
             uses: docker/login-action@v4
             with:
               username: ${{ vars.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}
              
           - name: Run container
             run: docker compose up -d

           - name: Execute remote SSH commands
             uses: appleboy/ssh-action@v1.2.1
             with:
                 host: ${{ secrets.HOST }}
                 username: ${{ secrets.USERNAME }}
                 key: ${{ secrets.KEY }}   # Or use 'password' if not using keys
                 port: 22
                 script: |
                    git clone
                    docker compose up -d
                    echo "Deployment successful!"