# Goal: To build and push the docker images

name: Docker build and Push

on:
   push:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: Docker setup
              uses: docker/setup-docker-actions@v5

            - name: Docker Login
              uses: docker/login-actions@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}