#Goal: To say Hello in the workflow and tell the title / Name of Repository

# start with naming your workflow
name: "Hello workflow"

# when the workflow runs
on:
 push: 

# what the workflow does
jobs:
 # name of your workflows
 greet:
   # where the job runs (OS)
  runs-on: ubuntu-latest
  # the sequence of steps the job does
  steps:
    - name: Say hello
      run: echo "hello Dosto"
repo-name:
 runs-on: ubuntu-latest
 steps:
  - name: Show Repository run-name: 
    run: echo "The Repo Name is ${{ github.event.repository.name }}"
 
