# Goal: To check if the python code is syntactically correct

name: Code Lint

on:
  push:
  
jobs:
  code-linter-and-test:
    strategy:
      matrix:
       python-version: ['3.12','3.13','3.14']

    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version}}

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Code Tests
        run: ruff check .

      - name: Code Tests
        run: pytest