# Goal: to deploy the index.html page to Github page (service to Github that runs static website)
name: Deploy Static Site

# when does this workflow run
on:
  # push:
  #  branches: [main]
  # you control and deploy by a button
  workflow_dispatch:  

# required permissons for the workflow
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup GitHub Pages Configuration
        uses: actions/configure-pages@v5

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.' # Location of your static files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
